apiVersion: operator.victoriametrics.com/v1beta1
kind: VLogs
metadata:
  name: victoria-logs
  namespace: victoria-logs
spec:
  retentionPeriod: "30d"
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Gi
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 4Gi
