---
- name: Create Cloud Plugin
  hosts: "{{ target_hosts | default('localhost') }}"
  vars_files: "{{ vault_files | default([]) }}"

  tasks:
    - name: Install Grafana Cloud plugin
      grafana.grafana.cloud_plugin:
        name: "grafana-github-datasource"
        version: "1.0.14"
        stack_slug: "{{ grafana_cloud_stack_slug }}"
        cloud_api_key: "{{ grafana_cloud_access_policy_token }}"
        state: present
      register: plugin_result

    - name: Display plugin installation result
      debug:
        var: plugin_result
