# =============================================================================
# Test Pulsar Deployment for Message Queue Monitoring
# =============================================================================
# Deploys: Apache Pulsar (standalone mode)
# Tests: MQ → Pulsar menu in SkyWalking
#
# Usage:
#   kubectl apply -f demo-pulsar.yaml -n skywalking
#   kubectl exec -it deploy/demo-pulsar -- bin/pulsar-client produce test -m "hello"
# =============================================================================

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-pulsar
  labels:
    app: demo-pulsar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-pulsar
  template:
    metadata:
      labels:
        app: demo-pulsar
    spec:
      containers:
        - name: pulsar
          image: apachepulsar/pulsar:3.3.0
          command: ["bin/pulsar", "standalone"]
          ports:
            - name: pulsar
              containerPort: 6650
            - name: http
              containerPort: 8080
            - name: metrics
              containerPort: 8080
          env:
            - name: PULSAR_MEM
              value: "-Xms256m -Xmx512m"
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /admin/v2/brokers/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: demo-pulsar
  labels:
    app: demo-pulsar
spec:
  type: ClusterIP
  ports:
    - name: pulsar
      port: 6650
    - name: http
      port: 8080
    - name: metrics
      port: 8080
  selector:
    app: demo-pulsar
