# =============================================================================
# Test RocketMQ Deployment for Message Queue Monitoring
# =============================================================================
# Deploys: Apache RocketMQ (NameServer + Broker) + Exporter
# Tests: MQ → RocketMQ menu in SkyWalking
#
# Usage:
#   kubectl apply -f demo-rocketmq.yaml -n skywalking
# =============================================================================

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-rocketmq-nameserver
  labels:
    app: demo-rocketmq
    component: nameserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-rocketmq
      component: nameserver
  template:
    metadata:
      labels:
        app: demo-rocketmq
        component: nameserver
    spec:
      containers:
        - name: nameserver
          image: apache/rocketmq:5.2.0
          command: ["sh", "mqnamesrv"]
          ports:
            - name: namesrv
              containerPort: 9876
          env:
            - name: JAVA_OPT
              value: "-Xms256m -Xmx256m"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: demo-rocketmq-nameserver
  labels:
    app: demo-rocketmq
spec:
  type: ClusterIP
  ports:
    - name: namesrv
      port: 9876
  selector:
    app: demo-rocketmq
    component: nameserver

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-rocketmq-broker
  labels:
    app: demo-rocketmq
    component: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-rocketmq
      component: broker
  template:
    metadata:
      labels:
        app: demo-rocketmq
        component: broker
    spec:
      containers:
        - name: broker
          image: apache/rocketmq:5.2.0
          command: ["sh", "-c", "mqbroker -n demo-rocketmq-nameserver:9876 autoCreateTopicEnable=true"]
          ports:
            - name: broker
              containerPort: 10911
          env:
            - name: JAVA_OPT
              value: "-Xms256m -Xmx256m"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: demo-rocketmq-broker
  labels:
    app: demo-rocketmq
spec:
  type: ClusterIP
  ports:
    - name: broker
      port: 10911
  selector:
    app: demo-rocketmq
    component: broker

---
# RocketMQ Exporter
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-rocketmq-exporter
  labels:
    app: demo-rocketmq
    component: exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-rocketmq
      component: exporter
  template:
    metadata:
      labels:
        app: demo-rocketmq
        component: exporter
    spec:
      containers:
        - name: exporter
          image: apache/rocketmq-exporter:0.0.2
          ports:
            - name: metrics
              containerPort: 5557
          env:
            - name: rocketmq.config.namesrvAddr
              value: "demo-rocketmq-nameserver:9876"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: demo-rocketmq
  labels:
    app: demo-rocketmq
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 5557
  selector:
    app: demo-rocketmq
    component: exporter
