# =============================================================================
# Test MongoDB Deployment for Database Monitoring
# =============================================================================
# Deploys: MongoDB + mongodb-exporter
# Tests: Database → MongoDB menu in SkyWalking
#
# Usage:
#   kubectl apply -f demo-mongodb.yaml -n skywalking
#   kubectl exec -it deploy/demo-mongodb -c mongodb -- mongosh
# =============================================================================

---
apiVersion: v1
kind: Secret
metadata:
  name: demo-mongodb-secret
  labels:
    app: demo-mongodb
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "test123"
  # Exporter connection string
  MONGODB_URI: "mongodb://admin:test123@localhost:27017/admin?authSource=admin"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-mongodb
  labels:
    app: demo-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-mongodb
  template:
    metadata:
      labels:
        app: demo-mongodb
    spec:
      containers:
        # MongoDB Server
        - name: mongodb
          image: mongo:7
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: demo-mongodb-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-mongodb-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

        # MongoDB Exporter (sidecar)
        - name: mongodb-exporter
          image: percona/mongodb_exporter:0.43.1
          ports:
            - name: metrics
              containerPort: 9216
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: demo-mongodb-secret
                  key: MONGODB_URI
          args:
            - --compatible-mode
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi

---
apiVersion: v1
kind: Service
metadata:
  name: demo-mongodb
  labels:
    app: demo-mongodb
spec:
  type: ClusterIP
  ports:
    - name: mongodb
      port: 27017
    - name: metrics
      port: 9216
  selector:
    app: demo-mongodb
