# =============================================================================
# Test Kafka Deployment for Message Queue Monitoring
# =============================================================================
# Deploys: Kafka (KRaft mode - no Zookeeper) + kafka-exporter
# Tests: MQ → Kafka menu in SkyWalking
#
# Usage:
#   kubectl apply -f demo-kafka.yaml -n skywalking
#   # Create test topic
#   kubectl exec -it deploy/demo-kafka -c kafka -- \
#     kafka-topics.sh --create --topic test --bootstrap-server localhost:9092
# =============================================================================

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-kafka
  labels:
    app: demo-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-kafka
  template:
    metadata:
      labels:
        app: demo-kafka
    spec:
      containers:
        # Kafka (KRaft mode - no Zookeeper needed)
        - name: kafka
          image: apache/kafka:3.8.0
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:9092,CONTROLLER://:9093"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://localhost:9092"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@localhost:9093"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: CLUSTER_ID
              value: "MkU3OEVBNTcwNTJENDM2Qk"
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi

        # Kafka Exporter (sidecar)
        - name: kafka-exporter
          image: danielqsj/kafka-exporter:v1.8.0
          ports:
            - name: metrics
              containerPort: 9308
          args:
            - --kafka.server=localhost:9092
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi

---
apiVersion: v1
kind: Service
metadata:
  name: demo-kafka
  labels:
    app: demo-kafka
spec:
  type: ClusterIP
  ports:
    - name: kafka
      port: 9092
    - name: metrics
      port: 9308
  selector:
    app: demo-kafka
