# =============================================================================
# OTel Collector Config for Test Deployments
# =============================================================================
# Scrapes metrics from all test deployments and forwards to SkyWalking OAP
#
# Usage:
#   kubectl apply -f otel-collector-demo.yaml -n skywalking
# =============================================================================

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-demo-config
  labels:
    app: otel-collector-demo
data:
  config.yaml: |
    receivers:
      prometheus:
        config:
          scrape_configs:
            # Gateway Tests
            - job_name: 'demo-nginx'
              scrape_interval: 15s
              static_configs:
                - targets: ['demo-nginx:9113']
              relabel_configs:
                - target_label: service
                  replacement: nginx::demo-nginx

            # Database Tests
            - job_name: 'demo-mysql'
              scrape_interval: 15s
              static_configs:
                - targets: ['demo-mysql:9104']
              relabel_configs:
                - target_label: service
                  replacement: mysql::demo-mysql

            - job_name: 'demo-postgresql'
              scrape_interval: 15s
              static_configs:
                - targets: ['demo-postgresql:9187']
              relabel_configs:
                - target_label: service
                  replacement: postgresql::demo-postgresql

            - job_name: 'demo-redis'
              scrape_interval: 15s
              static_configs:
                - targets: ['demo-redis:9121']
              relabel_configs:
                - target_label: service
                  replacement: redis::demo-redis

            - job_name: 'demo-mongodb'
              scrape_interval: 15s
              static_configs:
                - targets: ['demo-mongodb:9216']
              relabel_configs:
                - target_label: service
                  replacement: mongodb::demo-mongodb

            - job_name: 'demo-elasticsearch'
              scrape_interval: 15s
              static_configs:
                - targets: ['demo-elasticsearch:9114']
              relabel_configs:
                - target_label: service
                  replacement: elasticsearch::demo-elasticsearch

            # Message Queue Tests
            - job_name: 'demo-kafka'
              scrape_interval: 15s
              static_configs:
                - targets: ['demo-kafka:9308']
              relabel_configs:
                - target_label: service
                  replacement: kafka::demo-kafka

            - job_name: 'demo-rabbitmq'
              scrape_interval: 15s
              static_configs:
                - targets: ['demo-rabbitmq:15692']
              relabel_configs:
                - target_label: service
                  replacement: rabbitmq::demo-rabbitmq

            - job_name: 'demo-pulsar'
              scrape_interval: 15s
              static_configs:
                - targets: ['demo-pulsar:8080']
              relabel_configs:
                - target_label: service
                  replacement: pulsar::demo-pulsar

            - job_name: 'demo-activemq'
              scrape_interval: 15s
              static_configs:
                - targets: ['demo-activemq:9404']
              relabel_configs:
                - target_label: service
                  replacement: activemq::demo-activemq

            - job_name: 'demo-rocketmq'
              scrape_interval: 15s
              static_configs:
                - targets: ['demo-rocketmq:5557']
              relabel_configs:
                - target_label: service
                  replacement: rocketmq::demo-rocketmq

            # Data Processing Tests
            - job_name: 'demo-flink-jobmanager'
              scrape_interval: 15s
              static_configs:
                - targets: ['demo-flink-jobmanager:9249']
              relabel_configs:
                - target_label: service
                  replacement: flink::demo-flink-jobmanager

            - job_name: 'demo-flink-taskmanager'
              scrape_interval: 15s
              static_configs:
                - targets: ['demo-flink-taskmanager:9249']
              relabel_configs:
                - target_label: service
                  replacement: flink::demo-flink-taskmanager

    processors:
      batch:
        timeout: 10s

    exporters:
      otlp:
        endpoint: skywalking-oap:11800
        tls:
          insecure: true

    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [batch]
          exporters: [otlp]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector-demo
  labels:
    app: otel-collector-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector-demo
  template:
    metadata:
      labels:
        app: otel-collector-demo
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.121.0
          args: ["--config=/etc/otel/config.yaml"]
          volumeMounts:
            - name: config
              mountPath: /etc/otel
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
      volumes:
        - name: config
          configMap:
            name: otel-collector-demo-config
