# Object Storage Secret for LokiStack
#
# Create the secret before applying LokiStack CR
#
# Option 1: Apply this file (update values first!)
#   kubectl apply -f storage-secret.yaml
#
# Option 2: Create via kubectl
#   kubectl create secret generic lokistack-storage -n loki \
#     --from-literal=endpoint=http://minio:9000 \
#     --from-literal=bucketnames=loki-chunks \
#     --from-literal=access_key_id=<your-access-key> \
#     --from-literal=access_key_secret=<your-secret-key>

apiVersion: v1
kind: Secret
metadata:
  name: lokistack-storage
  namespace: loki
type: Opaque
stringData:
  # S3/MinIO
  endpoint: "http://minio:9000"
  bucketnames: "loki-chunks"
  access_key_id: "loki"
  access_key_secret: "supersecret"  # CHANGE THIS!

  # For AWS S3, use:
  # endpoint: "https://s3.us-east-1.amazonaws.com"
  # region: "us-east-1"

  # For GCS, use type: gcs in LokiStack and:
  # bucketname: "loki-chunks"
  # key.json: |
  #   { "type": "service_account", ... }

  # For Azure Blob, use type: azure in LokiStack and:
  # container: "loki-chunks"
  # account_name: "mystorageaccount"
  # account_key: "..."
