apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-querier
  namespace: loki
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: querier
    app.kubernetes.io/version: "${LOKI_VERSION}"
    app.kubernetes.io/instance: loki-dev
    app.kubernetes.io/part-of: logging-stack
    app.kubernetes.io/managed-by: kubectl
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki-querier
  template:
    metadata:
      labels:
        app: loki-querier
    spec:
      securityContext:
        fsGroup: 10001
      initContainers:
      - name: init-permissions
        image: busybox:1.35
        command: ['sh', '-c', 'chown -R 10001:10001 /loki']
        volumeMounts:
        - name: querier-cache
          mountPath: /loki
      containers:
      - name: loki-querier
        image: grafana/loki:${LOKI_VERSION}
        args:
        - -config.file=/etc/loki/querier.yaml
        - -target=querier
        - -config.expand-env=true
        ports:
        - containerPort: 3100
        - containerPort: 9095
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/loki
          readOnly: true
        - name: querier-cache
          mountPath: /loki
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-creds
              key: accesskey
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-creds
              key: secretkey
      volumes:
      - name: config-volume
        configMap:
          name: querier-config
      - name: querier-cache
        persistentVolumeClaim:
          claimName: querier-cache