apiVersion: 1

datasources:
  # VictoriaLogs - for log queries
  - name: VictoriaLogs
    type: victoriametrics-logs-datasource
    access: proxy
    url: http://victorialogs:9428
    isDefault: true
    editable: true

  # VictoriaMetrics - for recording rule metrics & alert state
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    editable: true
