apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: loki
  labels:
    app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush                               5
        Grace                               10
        Log_Level                           info
        Daemon                              off
        Parsers_File                        parsers.conf
        HTTP_Server                         On
        HTTP_Listen                         0.0.0.0
        HTTP_Port                           2020
        storage.path                        /fluent-bit/state/flb-storage
        storage.sync                        normal
        storage.checksum                    off
        storage.backlog.mem_limit           50M
        storage.max_chunks_up               256
        storage.delete_irrecoverable_chunks On

    [INPUT]
        Name                tail
        Buffer_Chunk_Size   32k
        Buffer_Max_Size     32k
        Path                /var/log/containers/*.log
        Read_from_Head      False
        Refresh_Interval    10
        Rotate_Wait         5
        Ignore_Older        1h
        Skip_Long_Lines     Off
        Skip_Empty_Lines    On
        DB                  /fluent-bit/state/flb_kube.db
        DB.sync             normal
        Mem_Buf_Limit       5MB
        Tag                 kube.*
        storage.type        filesystem
        multiline.parser    docker,cri

    [FILTER]
        Name                    kubernetes
        Match                   *
        Buffer_Size             64k
        Kube_URL                https://kubernetes.default.svc.cluster.local:443
        Kube_CA_File            /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File         /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix         kube.var.log.containers.
        Merge_Log               On
        Merge_Log_Key           log_processed
        Merge_Log_Trim          On
        Merge_Parser            json
        Keep_Log                On
        K8S-Logging.Parser      On
        K8S-Logging.Exclude     Off
        Labels                  On
        Annotations             Off
        Use_Kubelet             Off
        tls.verify              Off

    [OUTPUT]
        Name                    loki
        Match                   *
        host                    distributor.loki.svc.cluster.local
        port                    3100
        labels                  job=fluentbit,namespace=$kubernetes.namespace_name,pod=$kubernetes.pod_name,container=$kubernetes.container_name
        remove_keys             logtag,kubernetes.labels
        auto_kubernetes_labels  on
        workers                 1
        Retry_Limit             False

  parsers.conf: |
    [PARSER]
        Name   json
        Format json
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z
        Time_Keep Off

    [PARSER]
        Name docker
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%LZ
        Time_Keep On
        Time_Offset 0h

    [PARSER]
        Name cri
        Format regex
        Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
        Time_Keep On
