# =============================================================================
# Module 23 — Exercise 1: Query Ollama API
# =============================================================================
# Use the http data source to interact with a local Ollama instance.
# Demonstrates calling REST APIs from Terraform — a pattern used with
# any API (Vault, CMDB, compliance services, etc.)
#
# Prerequisites:
#   ollama serve                    # start Ollama server
#   ollama pull llama3.2:1b         # pull a small model
#
# Usage:
#   terraform init
#   terraform plan
#   terraform apply
# =============================================================================

terraform {
  required_version = ">= 1.15.0"

  required_providers {
    http = {
      source  = "hashicorp/http"
      version = "~> 3.4"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
  }
}

provider "http" {}
provider "local" {}

variable "ollama_base_url" {
  description = "Ollama API base URL"
  type        = string
  default     = "http://localhost:11434"
}

# --- Data Source 1: List installed models ---
data "http" "list_models" {
  url = "${var.ollama_base_url}/api/tags"

  request_headers = {
    Accept = "application/json"
  }
}

# --- Data Source 2: List running models ---
data "http" "running_models" {
  url = "${var.ollama_base_url}/api/ps"

  request_headers = {
    Accept = "application/json"
  }
}

# --- Parse the responses ---
locals {
  models_response = jsondecode(data.http.list_models.response_body)
  running_response = jsondecode(data.http.running_models.response_body)

  # Extract model names
  installed_models = [
    for model in local.models_response.models : model.name
  ]

  running_models = [
    for model in local.running_response.models : model.name
  ]

  # Extract model details
  model_details = {
    for model in local.models_response.models : model.name => {
      size           = model.size
      parameter_size = try(model.details.parameter_size, "unknown")
      family         = try(model.details.family, "unknown")
      quantization   = try(model.details.quantization_level, "unknown")
    }
  }
}

# --- Write a report ---
resource "local_file" "ollama_report" {
  filename = "${path.module}/output/ollama-report.txt"
  content  = <<-EOT
    === Ollama Model Report ===
    Generated by Terraform at ${timestamp()}

    Ollama URL: ${var.ollama_base_url}

    Installed Models (${length(local.installed_models)}):
    %{for name in local.installed_models~}
      - ${name}
    %{endfor~}

    Running Models (${length(local.running_models)}):
    %{for name in local.running_models~}
      - ${name}
    %{endfor~}
    %{if length(local.running_models) == 0~}
      (none currently loaded)
    %{endif~}

    Model Details:
    ${jsonencode(local.model_details)}
  EOT
}

# --- Write model details as JSON ---
resource "local_file" "models_json" {
  filename = "${path.module}/output/models.json"
  content  = jsonencode(local.model_details)
}

# --- Outputs ---
output "installed_models" {
  description = "List of installed Ollama models"
  value       = local.installed_models
}

output "running_models" {
  description = "Currently loaded models"
  value       = local.running_models
}

output "model_details" {
  description = "Details of each installed model"
  value       = local.model_details
}

output "ollama_status" {
  value = "Ollama is running with ${length(local.installed_models)} model(s) installed"
}
