# =============================================================================
# Elasticsearch Prometheus Exporter for SkyWalking
# =============================================================================
# Exports Elasticsearch metrics for SkyWalking monitoring
#
# Prerequisites:
#   - Elasticsearch cluster running
#   - Network access to Elasticsearch HTTP API
#
# Required OAP Rule: elasticsearch
# SkyWalking Menu: Database → Elasticsearch
#
# References:
#   - https://github.com/prometheus-community/elasticsearch_exporter
#   - https://skywalking.apache.org/docs/main/latest/en/setup/backend/backend-elasticsearch-monitoring/
# =============================================================================

---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-exporter-secret
  labels:
    app.kubernetes.io/name: elasticsearch-exporter
type: Opaque
stringData:
  # Elasticsearch credentials (if security enabled)
  ES_USERNAME: "elastic"
  ES_PASSWORD: "your-password"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-exporter
  labels:
    app.kubernetes.io/name: elasticsearch-exporter
    app.kubernetes.io/component: database-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: elasticsearch-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: elasticsearch-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9114"
    spec:
      containers:
        - name: elasticsearch-exporter
          image: quay.io/prometheuscommunity/elasticsearch-exporter:v1.8.0
          ports:
            - name: metrics
              containerPort: 9114
          env:
            - name: ES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-exporter-secret
                  key: ES_USERNAME
                  optional: true
            - name: ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-exporter-secret
                  key: ES_PASSWORD
                  optional: true
          args:
            # Elasticsearch URI (adjust based on your setup)
            - --es.uri=http://elasticsearch-service:9200
            # Enable all collectors
            - --es.all
            - --es.indices
            - --es.indices_settings
            - --es.indices_mappings
            - --es.shards
            - --es.snapshots
            - --es.cluster_settings
            # Timeout
            - --es.timeout=30s
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9114
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9114
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-exporter
  labels:
    app.kubernetes.io/name: elasticsearch-exporter
    app.kubernetes.io/component: database-monitoring
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9114
      targetPort: 9114
  selector:
    app.kubernetes.io/name: elasticsearch-exporter
