# =============================================================================
# MongoDB Prometheus Exporter for SkyWalking
# =============================================================================
# Exports MongoDB metrics for SkyWalking monitoring
#
# Prerequisites:
#   - MongoDB server/cluster running
#   - Database user with clusterMonitor role
#
# Required OAP Rule: mongodb
# SkyWalking Menu: Database → MongoDB
#
# References:
#   - https://github.com/percona/mongodb_exporter
#   - https://skywalking.apache.org/docs/main/latest/en/setup/backend/backend-mongodb-monitoring/
# =============================================================================

---
# Create monitoring user in MongoDB first:
# use admin
# db.createUser({
#   user: "exporter",
#   pwd: "your-password",
#   roles: [
#     { role: "clusterMonitor", db: "admin" },
#     { role: "read", db: "local" }
#   ]
# })

apiVersion: v1
kind: Secret
metadata:
  name: mongodb-exporter-secret
  labels:
    app.kubernetes.io/name: mongodb-exporter
type: Opaque
stringData:
  # MongoDB connection URI
  MONGODB_URI: "mongodb://exporter:your-password@mongodb-service:27017/admin?authSource=admin"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-exporter
  labels:
    app.kubernetes.io/name: mongodb-exporter
    app.kubernetes.io/component: database-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mongodb-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongodb-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9216"
    spec:
      containers:
        - name: mongodb-exporter
          image: percona/mongodb_exporter:0.43.1
          ports:
            - name: metrics
              containerPort: 9216
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-exporter-secret
                  key: MONGODB_URI
          args:
            - --collect-all
            - --compatible-mode
            # Discover all databases
            - --discovering-mode
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /
              port: 9216
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 9216
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-exporter
  labels:
    app.kubernetes.io/name: mongodb-exporter
    app.kubernetes.io/component: database-monitoring
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9216
      targetPort: 9216
  selector:
    app.kubernetes.io/name: mongodb-exporter

---
# =============================================================================
# MongoDB Replica Set Exporter (Optional)
# =============================================================================
# For MongoDB Replica Set, use the replica set connection string
# apiVersion: v1
# kind: Secret
# metadata:
#   name: mongodb-rs-exporter-secret
# type: Opaque
# stringData:
#   MONGODB_URI: "mongodb://exporter:password@mongo-0:27017,mongo-1:27017,mongo-2:27017/admin?replicaSet=rs0&authSource=admin"
