# =============================================================================
# Redis Prometheus Exporter for SkyWalking
# =============================================================================
# Exports Redis metrics for SkyWalking monitoring
#
# Prerequisites:
#   - Redis server running
#   - Redis password (if authentication enabled)
#
# Required OAP Rule: redis
# SkyWalking Menu: Database → Redis
#
# References:
#   - https://github.com/oliver006/redis_exporter
#   - https://skywalking.apache.org/docs/main/latest/en/setup/backend/backend-redis-monitoring/
# =============================================================================

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-exporter-secret
  labels:
    app.kubernetes.io/name: redis-exporter
type: Opaque
stringData:
  # Redis password (leave empty if no auth)
  REDIS_PASSWORD: "your-redis-password"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  labels:
    app.kubernetes.io/name: redis-exporter
    app.kubernetes.io/component: database-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9121"
    spec:
      containers:
        - name: redis-exporter
          image: oliver006/redis_exporter:v1.66.0
          ports:
            - name: metrics
              containerPort: 9121
          env:
            - name: REDIS_ADDR
              value: "redis://redis-service:6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-exporter-secret
                  key: REDIS_PASSWORD
                  optional: true
          args:
            - --include-system-metrics
            - --check-keys=*
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 9121
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 9121
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  labels:
    app.kubernetes.io/name: redis-exporter
    app.kubernetes.io/component: database-monitoring
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9121
      targetPort: 9121
  selector:
    app.kubernetes.io/name: redis-exporter

---
# =============================================================================
# Redis Cluster Exporter (Optional - for Redis Cluster mode)
# =============================================================================
# Uncomment if monitoring Redis Cluster
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: redis-cluster-exporter
#   labels:
#     app.kubernetes.io/name: redis-cluster-exporter
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app.kubernetes.io/name: redis-cluster-exporter
#   template:
#     metadata:
#       labels:
#         app.kubernetes.io/name: redis-cluster-exporter
#     spec:
#       containers:
#         - name: redis-exporter
#           image: oliver006/redis_exporter:v1.66.0
#           env:
#             - name: REDIS_ADDR
#               # Comma-separated list of Redis cluster nodes
#               value: "redis://redis-0:6379,redis://redis-1:6379,redis://redis-2:6379"
#           args:
#             - --is-cluster
