---
- name: Read Cloud API Keys
  hosts: "{{ target_hosts | default('localhost') }}"
  vars_files: "{{ vault_files | default([]) }}"

  tasks:
    - name: Check available Cloud API endpoints
      uri:
        url: "https://grafana.com/api/instances/{{ grafana_cloud_stack_slug }}"
        method: GET
        headers:
          Authorization: "Bearer {{ grafana_cloud_access_policy_token }}"
        return_content: yes
      register: instance_info

    - name: Display Cloud API authentication status
      debug:
        msg: "✅ Cloud API Authentication: SUCCESS"

    - name: Display available Cloud API endpoints
      debug:
        msg: "{{ item.rel }}: {{ item.href }}"
      loop: "{{ instance_info.json.links }}"

    - name: Display API key management limitation
      debug:
        msg: |
          ❌ API Key Management: NOT AVAILABLE via Cloud API

          Note: API keys must be managed through:
          1. Grafana instance UI: {{ grafana_url }}admin/api-keys
          2. Instance API (if available): {{ grafana_url }}api/auth/keys

          Cloud API is for instance-level management, not internal resource management.
