---
- name: Delete Cloud API Key
  hosts: "{{ target_hosts | default('localhost') }}"
  vars_files: "{{ vault_files | default([]) }}"

  tasks:
    - name: Delete Grafana Cloud API key
      grafana.grafana.cloud_api_key:
        name: "ansible-test-key"
        org_slug: "{{ grafana_cloud_org_slug }}"
        existing_cloud_api_key: "{{ grafana_cloud_api_key }}"
        state: absent
      register: delete_result
      ignore_errors: true

    - name: Display delete result
      debug:
        var: delete_result
