# =============================================================================
# SkyWalking Namespace Configuration
# =============================================================================
# Apply before Helm installation:
#   kubectl apply -f base/namespace.yaml
# =============================================================================

---
apiVersion: v1
kind: Namespace
metadata:
  name: skywalking
  labels:
    app.kubernetes.io/name: skywalking
    app.kubernetes.io/component: observability
    app.kubernetes.io/managed-by: helm
    # Enable Istio sidecar injection if using Istio
    # istio-injection: enabled
  annotations:
    # Resource quota enforcement
    scheduler.alpha.kubernetes.io/defaultTolerations: "[]"

---
# Resource Quota for the namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: skywalking-quota
  namespace: skywalking
spec:
  hard:
    requests.cpu: "20"
    requests.memory: "40Gi"
    limits.cpu: "40"
    limits.memory: "80Gi"
    persistentvolumeclaims: "20"
    pods: "50"

---
# Limit Range for default resource limits
apiVersion: v1
kind: LimitRange
metadata:
  name: skywalking-limits
  namespace: skywalking
spec:
  limits:
    - default:
        cpu: "1000m"
        memory: "1Gi"
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
      type: Container
