# =============================================================================
# Service Accounts for SkyWalking with AWS IRSA
# =============================================================================
# IAM Roles for Service Accounts (IRSA) configuration
#
# Prerequisites:
#   1. Create IAM role with trust policy for EKS OIDC provider
#   2. Attach required policies to the role
#   3. Update the role ARN in annotations below
#
# Create IAM Role (example using AWS CLI):
#   aws iam create-role --role-name skywalking-oap-role \
#     --assume-role-policy-document file://trust-policy.json
# =============================================================================

---
# OAP Service Account
# Used for: Kubernetes cluster coordination, optional AWS service access
apiVersion: v1
kind: ServiceAccount
metadata:
  name: skywalking-oap
  namespace: skywalking
  labels:
    app.kubernetes.io/name: skywalking
    app.kubernetes.io/component: oap
  annotations:
    # Uncomment and update with your IAM role ARN for IRSA
    # eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/skywalking-oap-role
    # eks.amazonaws.com/sts-regional-endpoints: "true"
    description: "Service account for SkyWalking OAP server"

---
# UI Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: skywalking-ui
  namespace: skywalking
  labels:
    app.kubernetes.io/name: skywalking
    app.kubernetes.io/component: ui
  annotations:
    description: "Service account for SkyWalking UI"

---
# BanyanDB Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: skywalking-banyandb
  namespace: skywalking
  labels:
    app.kubernetes.io/name: skywalking
    app.kubernetes.io/component: banyandb
  annotations:
    # Uncomment for IRSA if BanyanDB needs AWS access (e.g., S3 backup)
    # eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/skywalking-banyandb-role
    description: "Service account for BanyanDB storage"

---
# RBAC for OAP - Required for Kubernetes cluster coordination
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: skywalking-oap-role
  namespace: skywalking
rules:
  # Required for cluster coordination
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: skywalking-oap-rolebinding
  namespace: skywalking
subjects:
  - kind: ServiceAccount
    name: skywalking-oap
    namespace: skywalking
roleRef:
  kind: Role
  name: skywalking-oap-role
  apiGroup: rbac.authorization.k8s.io

---
# ClusterRole for cross-namespace pod discovery (if needed)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: skywalking-oap-cluster-role
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: skywalking-oap-cluster-rolebinding
subjects:
  - kind: ServiceAccount
    name: skywalking-oap
    namespace: skywalking
roleRef:
  kind: ClusterRole
  name: skywalking-oap-cluster-role
  apiGroup: rbac.authorization.k8s.io
