"""
Prometheus Installation and Testing Framework

This module provides the core test framework for validating Prometheus
deployments across multiple platforms (Minikube, EKS, GKE, AKS, Docker, Binary).
"""

__version__ = "0.1.0"
__author__ = "Prometheus Testing Team"

from .config import (
    TestConfig,
    PrometheusConfig,
    RunnerConfig,
    CredentialsConfig,
    K6Config,
    SanityTestConfig,
    IntegrationTestConfig,
    LoadTestConfig,
    StressTestConfig,
    PerformanceTestConfig,
    ScalabilityTestConfig,
    EnduranceTestConfig,
    ReliabilityTestConfig,
    ChaosTestConfig,
    RegressionTestConfig,
    SecurityTestConfig,
    ConfigValidationError,
    validate_config,
    load_config,
    expand_env_vars,
    DeploymentMode,
    VALID_PLATFORMS,
    MONOLITHIC_ONLY_PLATFORMS,
    CONFIG_SCHEMA,
)
from .models import (
    TestResult,
    TestError,
    TestStatus,
    TestSuiteResult,
    MetricSnapshot,
    ErrorCategory,
    ErrorSeverity,
)
from .deployer import (
    Platform,
    DeploymentStatus,
    DeployConfig,
    DeployResult,
    PlatformDeployer,
    KubernetesDeployer,
    MinikubeDeployer,
    MinikubeConfig,
    DockerDeployer,
    DockerConfig,
    BinaryDeployer,
    BinaryConfig,
    get_deployer,
    DeploymentMode as DeployerDeploymentMode,
)
from .eks_deployer import EKSDeployer, EKSConfig
from .gke_deployer import GKEDeployer, GKEConfig
from .aks_deployer import AKSDeployer, AKSConfig
from .prometheus_api import (
    PrometheusAPIClient,
    PrometheusAPIError,
    PrometheusConnectionError,
    PrometheusTimeoutError,
    PrometheusQueryError,
    HealthStatus,
    ReadinessStatus,
    QueryResult,
    RuntimeInfo,
    HealthCheckResult,
)
from .k6_runner import (
    K6Runner,
    K6RunnerError,
    K6Config as K6RunnerConfig,
    K6Metrics,
    K6Result,
    K6Stage,
    K6TestType,
    run_k6_load_test,
    run_k6_stress_test,
    run_k6_benchmark,
)
from .runner import (
    TestRunner,
    AsyncTestRunner,
    TestSpec,
    TestType,
    ExecutionMode,
    RunnerConfig as TestRunnerConfig,
    create_runner,
    run_tests,
)

__all__ = [
    # Config classes
    "TestConfig",
    "PrometheusConfig",
    "RunnerConfig",
    "CredentialsConfig",
    "K6Config",
    "SanityTestConfig",
    "IntegrationTestConfig",
    "LoadTestConfig",
    "StressTestConfig",
    "PerformanceTestConfig",
    "ScalabilityTestConfig",
    "EnduranceTestConfig",
    "ReliabilityTestConfig",
    "ChaosTestConfig",
    "RegressionTestConfig",
    "SecurityTestConfig",
    "ConfigValidationError",
    "validate_config",
    "load_config",
    "expand_env_vars",
    "DeploymentMode",
    "VALID_PLATFORMS",
    "MONOLITHIC_ONLY_PLATFORMS",
    "CONFIG_SCHEMA",
    # Model classes
    "TestResult",
    "TestError",
    "TestStatus",
    "TestSuiteResult",
    "MetricSnapshot",
    "ErrorCategory",
    "ErrorSeverity",
    # Deployer classes
    "Platform",
    "DeploymentStatus",
    "DeployConfig",
    "DeployResult",
    "PlatformDeployer",
    "KubernetesDeployer",
    "MinikubeDeployer",
    "MinikubeConfig",
    "DockerDeployer",
    "DockerConfig",
    "BinaryDeployer",
    "BinaryConfig",
    "get_deployer",
    "EKSDeployer",
    "EKSConfig",
    "GKEDeployer",
    "GKEConfig",
    "AKSDeployer",
    "AKSConfig",
    # Prometheus API Client
    "PrometheusAPIClient",
    "PrometheusAPIError",
    "PrometheusConnectionError",
    "PrometheusTimeoutError",
    "PrometheusQueryError",
    "HealthStatus",
    "ReadinessStatus",
    "QueryResult",
    "RuntimeInfo",
    "HealthCheckResult",
    # K6 Runner
    "K6Runner",
    "K6RunnerError",
    "K6RunnerConfig",
    "K6Metrics",
    "K6Result",
    "K6Stage",
    "K6TestType",
    "run_k6_load_test",
    "run_k6_stress_test",
    "run_k6_benchmark",
    # Test Runner
    "TestRunner",
    "AsyncTestRunner",
    "TestSpec",
    "TestType",
    "ExecutionMode",
    "TestRunnerConfig",
    "create_runner",
    "run_tests",
]
