apiVersion: v1
kind: Service
metadata:
  name: distributor
  namespace: loki
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: distributor
spec:
  ports:
  - name: http
    port: 3100
    targetPort: 3100
  - name: grpc
    port: 9095
    targetPort: 9095
  - name: memberlist
    port: 7946
    targetPort: 7946
  selector:
    app: loki-distributor
  type: LoadBalancer  # External access for log ingestion
---
apiVersion: v1
kind: Service
metadata:
  name: ingester
  namespace: loki
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: ingester
spec:
  clusterIP: None  # Headless for StatefulSet
  ports:
  - name: http
    port: 3100
    targetPort: 3100
  - name: grpc
    port: 9095
    targetPort: 9095
  - name: memberlist
    port: 7946
    targetPort: 7946
  selector:
    app: loki-ingester
---
apiVersion: v1
kind: Service
metadata:
  name: query-frontend
  namespace: loki
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: query-frontend
spec:
  ports:
  - name: http
    port: 3100
    targetPort: 3100
  - name: grpc
    port: 9095
    targetPort: 9095
  selector:
    app: loki-query-frontend
  type: LoadBalancer  # External access for queries
---
apiVersion: v1
kind: Service
metadata:
  name: query-scheduler
  namespace: loki
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: query-scheduler
spec:
  ports:
  - name: http
    port: 3100
    targetPort: 3100
  - name: grpc
    port: 9095
    targetPort: 9095
  selector:
    app: loki-query-scheduler
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: querier
  namespace: loki
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: querier
spec:
  ports:
  - name: http
    port: 3100
    targetPort: 3100
  - name: grpc
    port: 9095
    targetPort: 9095
  selector:
    app: loki-querier
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: index-gateway
  namespace: loki
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: index-gateway
spec:
  ports:
  - name: http
    port: 3100
    targetPort: 3100
  - name: grpc
    port: 9095
    targetPort: 9095
  selector:
    app: loki-index-gateway
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: compactor
  namespace: loki
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: compactor
spec:
  ports:
  - name: http
    port: 3100
    targetPort: 3100
  - name: grpc
    port: 9095
    targetPort: 9095
  selector:
    app: loki-compactor
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ruler
  namespace: loki
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: ruler
spec:
  ports:
  - name: http
    port: 3100
    targetPort: 3100
  - name: grpc
    port: 9095
    targetPort: 9095
  - name: memberlist
    port: 7946
    targetPort: 7946
  selector:
    app: loki-ruler
  type: ClusterIP