# =============================================================================
# ActiveMQ Prometheus Exporter for SkyWalking
# =============================================================================
# Exports ActiveMQ metrics via JMX for SkyWalking monitoring
#
# Prerequisites:
#   - ActiveMQ broker running with JMX enabled
#   - Network access to ActiveMQ JMX port
#
# Required OAP Rule: activemq
# SkyWalking Menu: MQ → ActiveMQ
#
# References:
#   - https://github.com/prometheus/jmx_exporter
#   - https://skywalking.apache.org/docs/main/latest/en/setup/backend/backend-activemq-monitoring/
# =============================================================================

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: activemq-jmx-config
  labels:
    app.kubernetes.io/name: activemq-exporter
data:
  config.yaml: |
    ---
    hostPort: localhost:1099
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true

    rules:
      # Broker metrics
      - pattern: 'org.apache.activemq<type=Broker, brokerName=(\w+)><>(\w+): (\d+)'
        name: activemq_broker_$2
        labels:
          broker: $1
        type: GAUGE

      # Queue metrics
      - pattern: 'org.apache.activemq<type=Broker, brokerName=(\w+), destinationType=Queue, destinationName=(\w+)><>(\w+): (\d+)'
        name: activemq_queue_$3
        labels:
          broker: $1
          queue: $2
        type: GAUGE

      # Topic metrics
      - pattern: 'org.apache.activemq<type=Broker, brokerName=(\w+), destinationType=Topic, destinationName=(\w+)><>(\w+): (\d+)'
        name: activemq_topic_$3
        labels:
          broker: $1
          topic: $2
        type: GAUGE

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq-exporter
  labels:
    app.kubernetes.io/name: activemq-exporter
    app.kubernetes.io/component: mq-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: activemq-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: activemq-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8161"
    spec:
      containers:
        - name: jmx-exporter
          image: bitnami/jmx-exporter:0.20.0
          ports:
            - name: metrics
              containerPort: 8161
          args:
            - "8161"
            - /config/config.yaml
          volumeMounts:
            - name: config
              mountPath: /config
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
      volumes:
        - name: config
          configMap:
            name: activemq-jmx-config

---
apiVersion: v1
kind: Service
metadata:
  name: activemq-exporter
  labels:
    app.kubernetes.io/name: activemq-exporter
    app.kubernetes.io/component: mq-monitoring
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 8161
      targetPort: 8161
  selector:
    app.kubernetes.io/name: activemq-exporter
