# =============================================================================
# Kafka Prometheus Exporter for SkyWalking
# =============================================================================
# Exports Kafka metrics for SkyWalking monitoring
#
# Prerequisites:
#   - Kafka cluster running
#   - Network access to Kafka brokers
#
# Required OAP Rule: kafka
# SkyWalking Menu: MQ → Kafka
#
# References:
#   - https://github.com/danielqsj/kafka_exporter
#   - https://skywalking.apache.org/docs/main/latest/en/setup/backend/backend-kafka-monitoring/
# =============================================================================

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  labels:
    app.kubernetes.io/name: kafka-exporter
    app.kubernetes.io/component: mq-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9308"
    spec:
      containers:
        - name: kafka-exporter
          image: danielqsj/kafka-exporter:v1.8.0
          ports:
            - name: metrics
              containerPort: 9308
          args:
            # Kafka broker addresses (comma-separated)
            - --kafka.server=kafka-service:9092
            # Enable consumer group metrics
            - --topic.filter=.*
            - --group.filter=.*
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9308
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9308
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter
  labels:
    app.kubernetes.io/name: kafka-exporter
    app.kubernetes.io/component: mq-monitoring
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9308
      targetPort: 9308
  selector:
    app.kubernetes.io/name: kafka-exporter
