# =============================================================================
# Auto-generated Terraform resources for imported Grafana folders
# Generated by: scripts/bulk-import-folders.sh
# =============================================================================
# After generating this file, run the import commands below to import
# existing folders into Terraform state.
# =============================================================================

resource "grafana_folder" "imported_dev_monitoring" {
  title = "Dev Monitoring"
  uid   = "dev-monitoring"
}

resource "grafana_folder" "imported_bfdav1oo7z5z4c" {
  title = "shiva Mahal"
  uid   = "bfdav1oo7z5z4c"
}
