# =============================================================================
# OpenTelemetry Collector for SkyWalking Monitoring
# =============================================================================
# Scrapes metrics from:
#   - Self-Observability: OAP, BanyanDB, Satellite
#   - Kubernetes: kube-state-metrics, cAdvisor
#   - Infrastructure: node-exporter (Linux VMs)
#
# Forwards to SkyWalking OAP via OTLP
#
# References:
#   - https://skywalking.apache.org/docs/main/latest/en/setup/backend/backend-telemetry/
#   - https://skywalking.apache.org/docs/main/latest/en/setup/backend/backend-k8s-monitoring-metrics-cadvisor/
# =============================================================================

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: skywalking
  labels:
    app.kubernetes.io/name: otel-collector
data:
  config.yaml: |
    receivers:
      prometheus:
        config:
          scrape_configs:
            # =================================================================
            # SELF-OBSERVABILITY
            # Required for: Self Observability menu in SkyWalking UI
            # =================================================================

            # OAP Server Metrics
            # Menu: Self Observability → OAP
            - job_name: 'skywalking-oap'
              scrape_interval: 15s
              static_configs:
                - targets: ['skywalking-oap-metrics:1234']
              relabel_configs:
                - target_label: service
                  replacement: skywalking-oap
                - target_label: cluster
                  replacement: minikube

            # BanyanDB Metrics (standalone mode - port 2121)
            # Note: BanyanDB exposes metrics on HTTP port
            # Menu: Self Observability → BanyanDB (when available)
            # Disabled for now - BanyanDB standalone doesn't expose metrics by default
            # - job_name: 'banyandb'
            #   scrape_interval: 15s
            #   static_configs:
            #     - targets: ['skywalking-banyandb-http:2121']

            # Satellite Metrics
            # Menu: Self Observability → Satellite
            - job_name: 'skywalking-satellite'
              scrape_interval: 15s
              static_configs:
                - targets: ['skywalking-satellite-metrics:1234']
              relabel_configs:
                - target_label: service
                  replacement: skywalking-satellite
                - target_label: cluster
                  replacement: minikube

            # =================================================================
            # KUBERNETES MONITORING
            # Required for: Kubernetes menu in SkyWalking UI
            # =================================================================

            # kube-state-metrics - Kubernetes Cluster State
            # Menu: Kubernetes → Cluster
            - job_name: 'kube-state-metrics'
              scrape_interval: 15s
              static_configs:
                - targets: ['kube-state-metrics:8080']
              relabel_configs:
                - target_label: cluster
                  replacement: minikube

            # cAdvisor - Container Metrics (via kubelet)
            # Menu: Kubernetes → Cluster (CPU/Memory usage)
            - job_name: 'cadvisor'
              scrape_interval: 15s
              scheme: https
              tls_config:
                ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                insecure_skip_verify: true
              bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              kubernetes_sd_configs:
                - role: node
              relabel_configs:
                - action: labelmap
                  regex: __meta_kubernetes_node_label_(.+)
                - target_label: __address__
                  replacement: kubernetes.default.svc:443
                - source_labels: [__meta_kubernetes_node_name]
                  regex: (.+)
                  target_label: __metrics_path__
                  replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
                - target_label: cluster
                  replacement: minikube
              metric_relabel_configs:
                - source_labels: [__name__]
                  regex: 'container_cpu_usage_seconds_total|container_memory_working_set_bytes|container_network_receive_bytes_total|container_network_transmit_bytes_total'
                  action: keep

            # =================================================================
            # INFRASTRUCTURE MONITORING
            # Required for: Infrastructure → Linux menu
            # =================================================================

            # Node Exporter - VM/Host Metrics
            - job_name: 'vm-monitoring'
              scrape_interval: 30s
              static_configs:
                - targets: ['node-exporter:9100']
              relabel_configs:
                - target_label: node_identifier_host_name
                  replacement: minikube-node

    processors:
      batch:
        timeout: 10s
        send_batch_size: 1000

      memory_limiter:
        check_interval: 1s
        limit_mib: 256
        spike_limit_mib: 64

    exporters:
      otlp:
        endpoint: skywalking-oap:11800
        tls:
          insecure: true

    extensions:
      health_check:
        endpoint: 0.0.0.0:13133

    service:
      extensions: [health_check]
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [memory_limiter, batch]
          exporters: [otlp]

      telemetry:
        logs:
          level: info

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: skywalking
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/component: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-collector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: otel-collector
    spec:
      serviceAccountName: otel-collector
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.121.0
          args:
            - --config=/etc/otel-collector/config.yaml
          ports:
            - name: otlp-grpc
              containerPort: 4317
            - name: otlp-http
              containerPort: 4318
            - name: metrics
              containerPort: 8888
            - name: health
              containerPort: 13133
          volumeMounts:
            - name: config
              mountPath: /etc/otel-collector
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /
              port: 13133
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 13133
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: otel-collector-config

---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: skywalking
  labels:
    app.kubernetes.io/name: otel-collector
spec:
  type: ClusterIP
  ports:
    - name: otlp-grpc
      port: 4317
    - name: otlp-http
      port: 4318
    - name: metrics
      port: 8888
  selector:
    app.kubernetes.io/name: otel-collector

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector
  namespace: skywalking

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector
rules:
  - apiGroups: [""]
    resources: ["nodes", "nodes/proxy", "nodes/metrics", "services", "endpoints", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]
  - nonResourceURLs: ["/metrics", "/metrics/cadvisor"]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-collector
subjects:
  - kind: ServiceAccount
    name: otel-collector
    namespace: skywalking
