# Optimized for MacBook Pro Development
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ingester-data-loki-ingester-0
  namespace: loki
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi  # Reduced from 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ingester-wal-loki-ingester-0
  namespace: loki
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Reduced from 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: compactor-data
  namespace: loki
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi  # Reduced from 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: querier-cache
  namespace: loki
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Reduced from 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: index-cache
  namespace: loki
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Reduced from 5Gi