apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: loki
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: storage
    app.kubernetes.io/version: "2025-09-07"
    app.kubernetes.io/instance: loki-dev
    app.kubernetes.io/part-of: logging-stack
    environment: development
spec:
  type: LoadBalancer
  ports:
  - name: api
    port: 9000
    targetPort: 9000
  - name: console
    port: 9001
    targetPort: 9001
  selector:
    app: minio
