---
- name: Read Contact Points
  hosts: "{{ target_hosts | default('localhost') }}"
  vars_files: "{{ vault_files | default([]) }}"

  tasks:
    - name: Get all contact points
      uri:
        url: "{{ grafana_url }}/api/v1/provisioning/contact-points"
        method: GET
        headers:
          Authorization: "Bearer {{ grafana_api_key }}"
        return_content: yes
      register: contact_points_result

    - name: Display contact points
      debug:
        var: contact_points_result.json
