apiVersion: v1
kind: Service
metadata:
  name: compactor
  namespace: loki
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: compactor
    app.kubernetes.io/version: "${LOKI_VERSION}"
    app.kubernetes.io/instance: loki-dev
    app.kubernetes.io/part-of: logging-stack
    environment: development
spec:
  ports:
  - name: http
    port: 3100
    targetPort: 3100
  - name: grpc
    port: 9095
    targetPort: 9095
  selector:
    app: loki-compactor
  type: ClusterIP
