apiVersion: v1
kind: Service
metadata:
  name: ingester
  namespace: loki
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: ingester
    app.kubernetes.io/version: "${LOKI_VERSION}"
    app.kubernetes.io/instance: loki-dev
    app.kubernetes.io/part-of: logging-stack
    environment: development
spec:
  clusterIP: None
  ports:
  - name: http
    port: 3100
    targetPort: 3100
  - name: grpc
    port: 9095
    targetPort: 9095
  - name: memberlist
    port: 7946
    targetPort: 7946
  selector:
    app: loki-ingester
