---
- name: Datasource Management Operations
  hosts: "{{ target_hosts | default('localhost') }}"
  vars_files:
  gather_facts: yes

  tasks:
    - name: Create Prometheus datasource
      grafana.grafana.datasource:
        dataSource: |
          {
            "name": "Prometheus",
            "type": "prometheus",
            "access": "proxy",
            "url": "http://localhost:9090",
            "isDefault": true,
            "jsonData": {
              "httpMethod": "POST",
              "manageAlerts": true,
              "prometheusType": "Prometheus",
              "cacheLevel": "High"
            }
          }
        grafana_url: "{{ grafana_url }}"
        grafana_api_key: "{{ grafana_api_key }}"
        state: present

    - name: Create multiple datasources
      grafana.grafana.datasource:
        dataSource: "{{ item }}"
        grafana_url: "{{ grafana_url }}"
        grafana_api_key: "{{ grafana_api_key }}"
        state: present
      loop:
        - name: "Loki"
          type: "loki"
          access: "proxy"
          url: "http://localhost:3100"
          jsonData:
            maxLines: 1000
        - name: "InfluxDB"
          type: "influxdb"
          access: "proxy"
          url: "http://localhost:8086"
          database: "telegraf"
          user: "admin"
          jsonData:
            httpMode: "GET"
        - name: "MySQL"
          type: "mysql"
          access: "proxy"
          url: "localhost:3306"
          database: "grafana"
          user: "grafana_user"
          secureJsonData:
            password: "<grafana_password>"

    - name: Get all datasources
      uri:
        url: "{{ grafana_url }}/api/datasources"
        method: GET
        headers:
          Authorization: "Bearer {{ grafana_api_key }}"
        return_content: yes
      register: datasources_result

    - name: Display datasources
      debug:
        var: datasources_result.json

    - name: Update Prometheus datasource configuration
      grafana.grafana.datasource:
        dataSource: |
          {
            "name": "Prometheus",
            "type": "prometheus",
            "access": "proxy",
            "url": "http://prometheus-server:9090",
            "isDefault": true,
            "jsonData": {
              "httpMethod": "GET",
              "manageAlerts": false,
              "prometheusType": "Prometheus",
              "cacheLevel": "Low",
              "timeInterval": "30s"
            }
          }
        grafana_url: "{{ grafana_url }}"
        grafana_api_key: "{{ grafana_api_key }}"
        state: present

    - name: Delete InfluxDB datasource
      grafana.grafana.datasource:
        dataSource:
          name: "InfluxDB"
        grafana_url: "{{ grafana_url }}"
        grafana_api_key: "{{ grafana_api_key }}"
        state: absent

    - name: Get updated datasources list
      uri:
        url: "{{ grafana_url }}/api/datasources"
        method: GET
        headers:
          Authorization: "Bearer {{ grafana_api_key }}"
        return_content: yes
      register: final_datasources_result

    - name: Display final datasources
      debug:
        var: final_datasources_result.json
