---
- name: Create Datasources
  hosts: "{{ target_hosts | default('localhost') }}"
  vars_files: "{{ vault_files | default([]) }}"

  tasks:
    - name: Create Prometheus datasource
      grafana.grafana.datasource:
        dataSource: |
          {
            "name": "Prometheus",
            "type": "prometheus",
            "access": "proxy",
            "url": "http://localhost:9090",
            "isDefault": true,
            "jsonData": {
              "httpMethod": "POST",
              "manageAlerts": true,
              "prometheusType": "Prometheus",
              "cacheLevel": "High"
            }
          }
        grafana_url: "{{ grafana_url }}"
        grafana_api_key: "{{ grafana_api_key }}"
        state: present

    - name: Create multiple datasources
      grafana.grafana.datasource:
        dataSource: "{{ item }}"
        grafana_url: "{{ grafana_url }}"
        grafana_api_key: "{{ grafana_api_key }}"
        state: present
      loop:
        - name: "Loki"
          type: "loki"
          access: "proxy"
          url: "http://localhost:3100"
          jsonData:
            maxLines: 1000
        - name: "InfluxDB"
          type: "influxdb"
          access: "proxy"
          url: "http://localhost:8086"
          database: "telegraf"
          user: "admin"
          jsonData:
            httpMode: "GET"
        - name: "MySQL"
          type: "mysql"
          access: "proxy"
          url: "localhost:3306"
          database: "grafana"
          user: "grafana_user"
          secureJsonData:
            password: "<grafana_password>"
