# Components to run. Default "all" runs Loki in single binary mode.
# "read" = querier + query-frontend (all in same process)
# "write" = distributor + compactor (all in same process)
# Supported: all, compactor, distributor, ingester, querier, query-scheduler,
# ingester-querier, query-frontend, index-gateway, ruler, table-manager, read, write

target: compactor
auth_enabled: false  # default = true

server:
  http_listen_port: 3100  # default = 3100
  grpc_listen_port: 9095  # default = 9095
  log_level: info  # default = "info", supported: debug, info, warn, error

ui:
  enabled: true  # default = false
  node_name: "${HOSTNAME:-compactor}"  # default = "<hostname>"
  advertise_addr: "${POD_IP}"  # default = ""
  cluster_name: "loki-microservices"  # default = ""
  debug: true  # default = false
  rejoin_interval: 3m  # default = 3m
  cluster_max_join_peers: 3  # default = 3
  enable_ipv6: false  # default = false
  discovery:
    join_peers:  # default = []
      - "query-frontend.loki.svc.cluster.local:3100"
      - "distributor.loki.svc.cluster.local:3100"
      - "ingester.loki.svc.cluster.local:3100"

common:
  instance_addr: "${POD_IP}"  # default = ""
  path_prefix: "/loki"  # default = ""
  storage:
    s3:
      endpoint: "minio.loki.svc.cluster.local:9000"
      bucketnames: "loki-chunks"
      access_key_id: "${MINIO_ACCESS_KEY}"
      secret_access_key: "${MINIO_SECRET_KEY}"
      insecure: true
      s3forcepathstyle: true
  replication_factor: 1  # default = 3
  ring:
    kvstore:
      store: memberlist  # default = "consul", supported: consul, etcd, inmemory, memberlist, multi
    instance_port: 9095  # default = 0 (uses server.grpc-listen-port)

storage_config:
  aws:
    endpoint: "minio.loki.svc.cluster.local:9000"
    bucketnames: "loki-chunks"
    access_key_id: "${MINIO_ACCESS_KEY}"
    secret_access_key: "${MINIO_SECRET_KEY}"
    s3forcepathstyle: true
    insecure: true
  index_cache_validity: 5m  # default = 5m
  max_parallel_get_chunk: 150  # default = 150
  max_chunk_batch_size: 50  # default = 50

memberlist:
  bind_addr: ["0.0.0.0"]  # default = []
  bind_port: 7946  # default = 7946
  advertise_addr: "${POD_IP}"  # default = ""
  advertise_port: 7946  # default = 7946
  join_members:  # default = []
    - "ingester.loki.svc.cluster.local:7946"
  abort_if_cluster_join_fails: false  # default = false
  stream_timeout: 2s  # default = 2s
  retransmit_factor: 4  # default = 4
  pull_push_interval: 30s  # default = 30s
  gossip_interval: 200ms  # default = 200ms
  gossip_nodes: 3  # default = 3
  compression_enabled: true  # default = true

compactor:
  working_directory: "/loki/compactor"  # default = "/var/loki/compactor"
  compaction_interval: 10m  # default = 10m
  apply_retention_interval: 0s  # default = 0s (run at same interval as compaction)
  retention_enabled: false  # default = false
  retention_delete_delay: 2h  # default = 2h
  retention_delete_worker_count: 150  # default = 150
  retention_table_timeout: 0s  # default = 0s
  delete_batch_size: 70  # default = 70
  delete_request_cancel_period: 24h  # default = 24h
  delete_max_interval: 24h  # default = 24h
  max_compaction_parallelism: 1  # default = 1
  upload_parallelism: 10  # default = 10
  tables_to_compact: 0  # default = 0 (compact all available tables)
  skip_latest_n_tables: 0  # default = 0
  compactor_ring:
    kvstore:
      store: memberlist  # default = "consul", supported: consul, etcd, inmemory, memberlist, multi
      prefix: collectors/  # default = "collectors/"
    heartbeat_period: 15s  # default = 15s
    heartbeat_timeout: 1m  # default = 1m
    instance_addr: "${POD_IP}"  # default = ""
    instance_port: 9095  # default = 0 (uses server.grpc-listen-port)
    instance_id: "${HOSTNAME:-compactor}"  # default = "<hostname>"
    zone_awareness_enabled: false  # default = false
    instance_enable_ipv6: false  # default = false
    tokens_file_path: ""  # default = "" (tokens not stored)

compactor_grpc_client:
  # The grpc_client block configures the gRPC client used to communicate between
  # a client and server component in Loki.
  # The CLI flags prefix for this block configuration is: compactor.grpc-client
  grpc_compression: 'snappy'  # default = "", supported: gzip, snappy
  connect_timeout: 5s  # default = 5s
  max_recv_msg_size: 104857600  # default = 4MB (4194304), setting to 100MB
  max_send_msg_size: 104857600  # default = 4MB (4194304), setting to 100MB
  use_gzip_compression: false  # default = false
  rate_limit: 0  # default = 0 (no limit)
  rate_limit_burst: 0  # default = 0 (no limit)
  backoff_on_ratelimits: false  # default = false
  backoff_config:
    min_period: 100ms  # default = 100ms
    max_period: 10s  # default = 10s
    max_retries: 10  # default = 10

analytics:
  reporting_enabled: false  # default = true

schema_config:
  configs:
    - from: 2024-04-01  # required, format: YYYY-MM-DD
      store: tsdb  # default = "", supported: tsdb, boltdb-shipper
      object_store: s3  # default = "", supported: aws/s3, azure, gcs, alibabacloud, bos, cos, swift, filesystem
      schema: v13  # default = "", current recommended: v13
      index:
        prefix: index_  # default = ""
        period: 24h  # required
        path_prefix: index/  # default = "index/"
      row_shards: 16  # default = 16, only used if schema is v10 or greater
