target: querier
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: info

ui:
  enabled: true
  node_name: "${HOSTNAME:-querier}"
  advertise_addr: "${POD_IP}"
  cluster_name: "loki-microservices"
  debug: true
  discovery:
    join_peers:
      - "query-frontend.loki.svc.cluster.local:3100"
      - "distributor.loki.svc.cluster.local:3100"
      - "ingester.loki.svc.cluster.local:3100"

common:
  instance_addr: "${POD_IP}"
  path_prefix: "/loki"
  storage:
    s3:
      endpoint: "minio.loki.svc.cluster.local:9000"
      bucketnames: "loki-chunks"
      access_key_id: "${MINIO_ACCESS_KEY}"
      secret_access_key: "${MINIO_SECRET_KEY}"
      insecure: true
      s3forcepathstyle: true
  replication_factor: 1
  ring:
    kvstore:
      store: memberlist
    instance_port: 9095
  compactor_address: "compactor.loki.svc.cluster.local:3100"

storage_config:
  aws:
    endpoint: "minio.loki.svc.cluster.local:9000"
    bucketnames: "loki-chunks"
    access_key_id: "${MINIO_ACCESS_KEY}"
    secret_access_key: "${MINIO_SECRET_KEY}"
    s3forcepathstyle: true
    insecure: true
  tsdb_shipper:
    active_index_directory: "/loki/tsdb-index"
    cache_location: "/loki/tsdb-cache"
    cache_ttl: 24h

memberlist:
  bind_addr: ["0.0.0.0"]
  bind_port: 7946
  advertise_addr: "${POD_IP}"
  advertise_port: 7946
  join_members:
    - "ingester.loki.svc.cluster.local:7946"
  abort_if_cluster_join_fails: false

querier:
  tail_max_duration: 12h
  query_ingesters_within: 0h
  engine:
    max_look_back_period: 168h
  max_concurrent: 4
frontend_worker:
  scheduler_address: "query-scheduler.loki.svc.cluster.local:9095"

analytics:
  reporting_enabled: false

schema_config:
  configs:
    - from: 2024-04-01
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h
