target: query-frontend
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: info

ui:
  enabled: true
  node_name: "${HOSTNAME:-query-frontend}"
  advertise_addr: "${POD_IP}"
  cluster_name: "loki-microservices"
  debug: true

common:
  instance_addr: "${POD_IP}"
  path_prefix: "/loki"
  storage:
    s3:
      endpoint: "minio.loki.svc.cluster.local:9000"
      bucketnames: "loki-chunks"
      access_key_id: "${MINIO_ACCESS_KEY}"
      secret_access_key: "${MINIO_SECRET_KEY}"
      insecure: true
      s3forcepathstyle: true
  replication_factor: 1
  compactor_address: "compactor.loki.svc.cluster.local:3100"
  ring:
    kvstore:
      store: memberlist

memberlist:
  bind_addr: ["0.0.0.0"]
  bind_port: 7946
  advertise_addr: "${POD_IP}"
  advertise_port: 7946
  join_members: ["distributor.loki.svc.cluster.local:7946", "ingester.loki.svc.cluster.local:7946"]

storage_config:
  aws:
    endpoint: "minio.loki.svc.cluster.local:9000"
    bucketnames: "loki-chunks"
    access_key_id: "${MINIO_ACCESS_KEY}"
    secret_access_key: "${MINIO_SECRET_KEY}"
    s3forcepathstyle: true
    insecure: true

distributor:
  ring:
    kvstore:
      store: memberlist
    instance_port: 9095

ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1

frontend:
  max_outstanding_per_tenant: 100
  scheduler_address: "query-scheduler.loki.svc.cluster.local:9095"

analytics:
  reporting_enabled: false

schema_config:
  configs:
    - from: 2024-04-01
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h
