target: query-scheduler
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: info

ui:
  enabled: true
  node_name: "${HOSTNAME:-query-scheduler}"
  advertise_addr: "${POD_IP}"
  cluster_name: "loki-microservices"

common:
  instance_addr: "${POD_IP}"
  path_prefix: "/loki"
  ring:
    kvstore:
      store: memberlist
    instance_port: 9095

storage_config:
  tsdb_shipper:
    active_index_directory: "/loki/tsdb-index"
    cache_location: "/loki/tsdb-cache"

memberlist:
  bind_addr: ["0.0.0.0"]
  bind_port: 7946
  advertise_addr: "${POD_IP}"
  advertise_port: 7946
  join_members:
    - "distributor.loki.svc.cluster.local:7946"
    - "ingester.loki.svc.cluster.local:7946"
  abort_if_cluster_join_fails: false

query_scheduler:
  max_outstanding_requests_per_tenant: 32000
  grpc_client_config:
    max_recv_msg_size: 104857600
    max_send_msg_size: 104857600
  scheduler_ring:
    kvstore:
      store: memberlist

analytics:
  reporting_enabled: false

schema_config:
  configs:
    - from: 2024-04-01
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h
