target: ruler
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: info

ui:
  enabled: true
  node_name: "${HOSTNAME:-ruler}"
  advertise_addr: "${POD_IP}"
  cluster_name: "loki-microservices"
  debug: true
  rejoin_interval: 3m
  cluster_max_join_peers: 4
  enable_ipv6: false
  discovery:
    join_peers:
      - "query-frontend.loki.svc.cluster.local:3100"
      - "distributor.loki.svc.cluster.local:3100"
      - "ingester.loki.svc.cluster.local:3100"
      - "querier.loki.svc.cluster.local:3100"

common:
  instance_addr: "${POD_IP}"
  path_prefix: "/loki"
  storage:
    s3:
      endpoint: "minio.loki.svc.cluster.local:9000"
      bucketnames: "loki-chunks"
      access_key_id: "${MINIO_ACCESS_KEY}"
      secret_access_key: "${MINIO_SECRET_KEY}"
      insecure: true
      s3forcepathstyle: true
  replication_factor: 1  # Set to 1 for single-replica development setup (global)
  ring:
    kvstore:
      store: memberlist
      prefix: collectors/  # default = "collectors/"
    instance_port: 9095
    heartbeat_period: 5s  # default = 5s
    heartbeat_timeout: 1m  # default = 1m
    num_tokens: 128  # default = 128
    replication_factor: 1  # Set to 1 for single-replica development setup (ring-specific)

storage_config:
  aws:
    endpoint: "minio.loki.svc.cluster.local:9000"
    bucketnames: "loki-chunks"
    access_key_id: "${MINIO_ACCESS_KEY}"
    secret_access_key: "${MINIO_SECRET_KEY}"
    s3forcepathstyle: true
    insecure: true

memberlist:
  bind_addr: ["0.0.0.0"]
  bind_port: 7946
  advertise_addr: "${POD_IP}"
  advertise_port: 7946
  join_members:
    - "distributor.loki.svc.cluster.local:7946"
    - "ingester.loki.svc.cluster.local:7946"
  abort_if_cluster_join_fails: false

ruler:
  storage:
    type: local
    local:
      directory: "/loki/rules"
  rule_path: "/loki/rules-temp"
  enable_api: true

analytics:
  reporting_enabled: false

schema_config:
  configs:
    - from: 2024-04-01
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h
