apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: loki
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://query-frontend.loki.svc.cluster.local:3100
      isDefault: true
      editable: true
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus.loki.svc.cluster.local:9090
      isDefault: false
      editable: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-config
  namespace: loki
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      updateIntervalSeconds: 10
      allowUiUpdates: true
      options:
        path: /var/lib/grafana/dashboards
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: loki
data:
  loki-logs.json: |
    {
      "dashboard": {
        "id": null,
        "title": "Loki Logs Dashboard",
        "tags": ["loki"],
        "style": "dark",
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "Log Volume",
            "type": "stat",
            "targets": [
              {
                "expr": "sum(rate({job=~\".+\"}[5m]))",
                "refId": "A"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "color": {
                  "mode": "thresholds"
                },
                "mappings": [],
                "thresholds": {
                  "steps": [
                    {
                      "color": "green",
                      "value": null
                    }
                  ]
                },
                "unit": "logs/sec"
              }
            },
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 0,
              "y": 0
            }
          },
          {
            "id": 2,
            "title": "Recent Logs",
            "type": "logs",
            "targets": [
              {
                "expr": "{job=~\".+\"}",
                "refId": "A"
              }
            ],
            "gridPos": {
              "h": 16,
              "w": 24,
              "x": 0,
              "y": 8
            },
            "options": {
              "showTime": true,
              "showLabels": true,
              "showCommonLabels": false,
              "wrapLogMessage": true,
              "prettifyLogMessage": false,
              "enableLogDetails": true,
              "dedupStrategy": "none",
              "sortOrder": "Descending"
            }
          }
        ],
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "timepicker": {},
        "templating": {
          "list": []
        },
        "annotations": {
          "list": []
        },
        "refresh": "5s",
        "schemaVersion": 27,
        "version": 0,
        "links": []
      }
    }
  loki-metrics.json: |
    {
      "dashboard": {
        "id": null,
        "title": "Loki & Fluent Bit Metrics",
        "tags": ["loki", "metrics"],
        "style": "dark",
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "Ingestion Rate",
            "type": "graph",
            "targets": [
              {
                "expr": "sum(rate(loki_distributor_ingester_appends_total[5m]))",
                "refId": "A",
                "legendFormat": "Ingestion Rate"
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 0,
              "y": 0
            },
            "yAxes": [
              {
                "label": "logs/sec"
              }
            ]
          },
          {
            "id": 2,
            "title": "Query Rate",
            "type": "graph",
            "targets": [
              {
                "expr": "sum(rate(loki_request_duration_seconds_count{route=\"loki_api_v1_query_range\"}[5m]))",
                "refId": "A",
                "legendFormat": "Query Rate"
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 12,
              "y": 0
            },
            "yAxes": [
              {
                "label": "queries/sec"
              }
            ]
          },
          {
            "id": 3,
            "title": "Fluent Bit Output Records",
            "type": "graph",
            "targets": [
              {
                "expr": "sum(rate(fluentbit_output_proc_records_total[5m]))",
                "refId": "A",
                "legendFormat": "Records/sec"
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 0,
              "y": 8
            },
            "yAxes": [
              {
                "label": "records/sec"
              }
            ]
          },
          {
            "id": 4,
            "title": "Loki Components Status",
            "type": "stat",
            "targets": [
              {
                "expr": "up{job=~\"loki-.*\"}",
                "refId": "A",
                "legendFormat": "{{job}}"
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 12,
              "y": 8
            },
            "fieldConfig": {
              "defaults": {
                "color": {
                  "mode": "thresholds"
                },
                "thresholds": {
                  "steps": [
                    {
                      "color": "red",
                      "value": 0
                    },
                    {
                      "color": "green",
                      "value": 1
                    }
                  ]
                }
              }
            }
          }
        ],
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "refresh": "5s",
        "schemaVersion": 27,
        "version": 0
      }
    }