apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: loki
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: visualization
    app.kubernetes.io/instance: loki-dev
    app.kubernetes.io/part-of: logging-stack
    environment: development
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: grafana