apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: loki
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/instance: loki-dev
    app.kubernetes.io/part-of: logging-stack
    environment: development
spec:
  type: LoadBalancer
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app: prometheus