# Fluent Bit Configuration - JSON Logs to Loki
# Tails JSON log files and forwards to Loki with parsing

service:
  log_level: info
  http_server: on
  http_listen: 0.0.0.0
  http_port: 2020

parsers:
  - name: json
    format: json
    time_key: timestamp
    time_format: "%Y-%m-%dT%H:%M:%S.%L%z"
    time_keep: on

pipeline:
  inputs:
    - name: tail
      path: ${HOME}/data/log/logger/*.log
      read_from_head: false
      refresh_interval: 10
      ignore_older: 1h
      tag: local.*
      parser: json

  outputs:
    - name: loki
      match: '*'
      host: 127.0.0.1
      port: 3100
      labels: service_name=fluent-bit,source=fuzzy-train-log,log_type=application,log_format=json
