# Fluent Bit YAML Configuration
# https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/yaml
# works with Fluent Bit v4.1.x

service:
  flush: 1
  grace: 5
  log_level: info
  http_server: on
  http_listen: 0.0.0.0
  http_port: 2020

pipeline:
  inputs:
    - name: tail
      path: ${HOME}/data/log/logger/*.log
      tag: local.*

  outputs:
    - name: loki
      match: '*'
      host: 127.0.0.1
      port: 3100
      labels: job=fluentbit,source=local
    # uncomment for debugging
    # - name: stdout
    #   match: '*'
    #   format: json_lines # msgpack, json, json_lines and json_stream
