---
- name: Create Cloud Stack
  hosts: "{{ target_hosts | default('localhost') }}"
  vars_files: "{{ vault_files | default([]) }}"

  tasks:
    - name: Create Grafana Cloud stack
      grafana.grafana.cloud_stack:
        name: "ansible-test-stack"
        stack_slug: "ansible-test-stack"
        cloud_api_key: "{{ grafana_cloud_api_key }}"
        org_slug: "{{ grafana_cloud_org_slug }}"
        region: "us"
        delete_protection: true
        state: present
      register: stack_result

    - name: Display stack creation result
      debug:
        var: stack_result
