---
- name: Delete Cloud Stack
  hosts: "{{ target_hosts | default('localhost') }}"
  vars_files: "{{ vault_files | default([]) }}"

  tasks:
    - name: Delete Grafana Cloud stack
      grafana.grafana.cloud_stack:
        name: "ansible-test-stack"
        stack_slug: "ansible-test-stack"
        cloud_api_key: "{{ grafana_cloud_access_policy_token }}"
        org_slug: "{{ grafana_cloud_org_slug }}"
        delete_protection: false
        state: absent
      register: delete_result
      ignore_errors: true

    - name: Display stack deletion result
      debug:
        var: delete_result
