# Optimized for MacBook Pro Development
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: loki
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi  # Reduced from 10Gi
