apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: monitoring
  labels:
    dashboards: "grafana"
spec:
  config:
    server:
      root_url: http://localhost:3000
    auth.anonymous:
      enabled: "true"
      org_role: Admin
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              image: grafana/grafana-oss:13.2.0
